name: Supabase

on:
  pull_request:

permissions:
  contents: read

jobs:
  db:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: supabase/setup-cli@v2.1.1
        with:
          version: 2.90.0
      - uses: pnpm/action-setup@v6.0.3
        with:
          version: 10.33.0
      - uses: actions/setup-node@v6.4.0
        with:
          node-version: 24.14.0
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile
      - run: supabase start
      - run: pnpm db:reset
      - run: pnpm db:test
      - run: pnpm db:types:verify
      - if: ${{ always() }}
        run: supabase stop --no-backup
